/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAccessRouteImport } from './routes/admin/access'
import { Route as AdminPescaRouteImport } from './routes/admin/pesca'
import { Route as AdminSpotsRouteImport } from './routes/admin/spots'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as ApiMeRouteImport } from './routes/api/me'
import { Route as ApiSpotsRouteImport } from './routes/api/spots'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiImagesKindIdRouteImport } from './routes/api/images/$kind/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAccessRoute = AdminAccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPescaRoute = AdminPescaRouteImport.update({
  id: '/pesca',
  path: '/pesca',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSpotsRoute = AdminSpotsRouteImport.update({
  id: '/spots',
  path: '/spots',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiMeRoute = ApiMeRouteImport.update({
  id: '/api/me',
  path: '/api/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSpotsRoute = ApiSpotsRouteImport.update({
  id: '/api/spots',
  path: '/api/spots',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImagesKindIdRoute = ApiImagesKindIdRouteImport.update({
  id: '/api/images/$kind/$id',
  path: '/api/images/$kind/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/access': typeof AdminAccessRoute
  '/admin/pesca': typeof AdminPescaRoute
  '/admin/spots': typeof AdminSpotsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/me': typeof ApiMeRoute
  '/api/spots': typeof ApiSpotsRoute
  '/admin/': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/images/$kind/$id': typeof ApiImagesKindIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/access': typeof AdminAccessRoute
  '/admin/pesca': typeof AdminPescaRoute
  '/admin/spots': typeof AdminSpotsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/me': typeof ApiMeRoute
  '/api/spots': typeof ApiSpotsRoute
  '/admin': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/images/$kind/$id': typeof ApiImagesKindIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/access': typeof AdminAccessRoute
  '/admin/pesca': typeof AdminPescaRoute
  '/admin/spots': typeof AdminSpotsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/me': typeof ApiMeRoute
  '/api/spots': typeof ApiSpotsRoute
  '/admin/': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/images/$kind/$id': typeof ApiImagesKindIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/admin/access'
    | '/admin/pesca'
    | '/admin/spots'
    | '/admin/users'
    | '/api/me'
    | '/api/spots'
    | '/admin/'
    | '/api/auth/$'
    | '/api/images/$kind/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/access'
    | '/admin/pesca'
    | '/admin/spots'
    | '/admin/users'
    | '/api/me'
    | '/api/spots'
    | '/admin'
    | '/api/auth/$'
    | '/api/images/$kind/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/admin/access'
    | '/admin/pesca'
    | '/admin/spots'
    | '/admin/users'
    | '/api/me'
    | '/api/spots'
    | '/admin/'
    | '/api/auth/$'
    | '/api/images/$kind/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiMeRoute: typeof ApiMeRoute
  ApiSpotsRoute: typeof ApiSpotsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiImagesKindIdRoute: typeof ApiImagesKindIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/access': {
      id: '/admin/access'
      path: '/access'
      fullPath: '/admin/access'
      preLoaderRoute: typeof AdminAccessRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/pesca': {
      id: '/admin/pesca'
      path: '/pesca'
      fullPath: '/admin/pesca'
      preLoaderRoute: typeof AdminPescaRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/spots': {
      id: '/admin/spots'
      path: '/spots'
      fullPath: '/admin/spots'
      preLoaderRoute: typeof AdminSpotsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/me': {
      id: '/api/me'
      path: '/api/me'
      fullPath: '/api/me'
      preLoaderRoute: typeof ApiMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/spots': {
      id: '/api/spots'
      path: '/api/spots'
      fullPath: '/api/spots'
      preLoaderRoute: typeof ApiSpotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/images/$kind/$id': {
      id: '/api/images/$kind/$id'
      path: '/api/images/$kind/$id'
      fullPath: '/api/images/$kind/$id'
      preLoaderRoute: typeof ApiImagesKindIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAccessRoute: typeof AdminAccessRoute
  AdminPescaRoute: typeof AdminPescaRoute
  AdminSpotsRoute: typeof AdminSpotsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAccessRoute: AdminAccessRoute,
  AdminPescaRoute: AdminPescaRoute,
  AdminSpotsRoute: AdminSpotsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiMeRoute: ApiMeRoute,
  ApiSpotsRoute: ApiSpotsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiImagesKindIdRoute: ApiImagesKindIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
